on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: check-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: check
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm test:coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}